### ISSUE TITLE
TODO: Vypínání animace vln

### ISSUE THREAD

**Issue by vvolhejn** [preissj/Symposion-2015#1]
Pro pomalejší počítače potřebujeme možnost, jak vypnout vlnění.

**Comment by preissj** [comment]
Ta použitá knihovna k tomu má jednoduchý příkaz. Každopádně náš canvas je teď na dost malé ploše, takže to utáhnou snad všechny počítače. Ty, co by to nezvládly, pravděpodobně ani nemají podporu WebGL, takže se jim efekt nezobrazí. Dát tam tlačítko pro vypnutí by kazilo celkový dojem a působilo dost neohrabaně. A to, jestli se to bude sekat nebo ne, jen tak jednoduše kódem nezjistíš. Musel bys měřit FPS a to je už docela zbytečné. Tohle bych tedy neřešil, případně až podle feedback.
