### ISSUE TITLE
TODO: dotáhnout popup do použitelnosti

### ISSUE THREAD

**Issue by vvolhejn** [preissj/Symposion-2015#2]
Někdo má bug, kde se nezobrazí vůbec žádný popis přednášky.

Nejde scrollovat a na mobilu je proto úplně nepoužitelný. Taky potřebujeme přidat podporu pro vypínání pomocí Escape a křížku. Na mobilu by se měl zobrazovat "fullscreen". Možná taky zvýšit opacity.

**Comment by preissj** [comment]
Pop-up upraven. Měl by vyhovovat...
